package com.kgc.provider.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goods_group
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GoodsGroup implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_group.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_group.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_group.good_sort
     *
     * @mbg.generated
     */
    private String goodSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_group.id
     *
     * @return the value of goods_group.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_group.id
     *
     * @param id the value for goods_group.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_group.group_name
     *
     * @return the value of goods_group.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_group.group_name
     *
     * @param groupName the value for goods_group.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_group.good_sort
     *
     * @return the value of goods_group.good_sort
     *
     * @mbg.generated
     */
    public String getGoodSort() {
        return goodSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_group.good_sort
     *
     * @param goodSort the value for goods_group.good_sort
     *
     * @mbg.generated
     */
    public void setGoodSort(String goodSort) {
        this.goodSort = goodSort;
    }
}