package com.kgc.provider.dto;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goods
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Good implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_id
     *
     * @mbg.generated
     */
    private String goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_name
     *
     * @mbg.generated
     */
    private String goodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_price
     *
     * @mbg.generated
     */
    private Double goodPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_stock
     *
     * @mbg.generated
     */
    private Integer goodStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_sales
     *
     * @mbg.generated
     */
    private Integer goodSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.shelf_time
     *
     * @mbg.generated
     */
    private Date shelfTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_image
     *
     * @mbg.generated
     */
    private String goodImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_content
     *
     * @mbg.generated
     */
    private String goodContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_sort
     *
     * @mbg.generated
     */
    private Integer goodSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_id
     *
     * @return the value of goods.good_id
     *
     * @mbg.generated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_id
     *
     * @param goodId the value for goods.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_name
     *
     * @return the value of goods.good_name
     *
     * @mbg.generated
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_name
     *
     * @param goodName the value for goods.good_name
     *
     * @mbg.generated
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_price
     *
     * @return the value of goods.good_price
     *
     * @mbg.generated
     */
    public Double getGoodPrice() {
        return goodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_price
     *
     * @param goodPrice the value for goods.good_price
     *
     * @mbg.generated
     */
    public void setGoodPrice(Double goodPrice) {
        this.goodPrice = goodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_stock
     *
     * @return the value of goods.good_stock
     *
     * @mbg.generated
     */
    public Integer getGoodStock() {
        return goodStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_stock
     *
     * @param goodStock the value for goods.good_stock
     *
     * @mbg.generated
     */
    public void setGoodStock(Integer goodStock) {
        this.goodStock = goodStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_sales
     *
     * @return the value of goods.good_sales
     *
     * @mbg.generated
     */
    public Integer getGoodSales() {
        return goodSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_sales
     *
     * @param goodSales the value for goods.good_sales
     *
     * @mbg.generated
     */
    public void setGoodSales(Integer goodSales) {
        this.goodSales = goodSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.shelf_time
     *
     * @return the value of goods.shelf_time
     *
     * @mbg.generated
     */
    public Date getShelfTime() {
        return shelfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.shelf_time
     *
     * @param shelfTime the value for goods.shelf_time
     *
     * @mbg.generated
     */
    public void setShelfTime(Date shelfTime) {
        this.shelfTime = shelfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_image
     *
     * @return the value of goods.good_image
     *
     * @mbg.generated
     */
    public String getGoodImage() {
        return goodImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_image
     *
     * @param goodImage the value for goods.good_image
     *
     * @mbg.generated
     */
    public void setGoodImage(String goodImage) {
        this.goodImage = goodImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_content
     *
     * @return the value of goods.good_content
     *
     * @mbg.generated
     */
    public String getGoodContent() {
        return goodContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_content
     *
     * @param goodContent the value for goods.good_content
     *
     * @mbg.generated
     */
    public void setGoodContent(String goodContent) {
        this.goodContent = goodContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_delete
     *
     * @return the value of goods.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_delete
     *
     * @param isDelete the value for goods.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_sort
     *
     * @return the value of goods.good_sort
     *
     * @mbg.generated
     */
    public Integer getGoodSort() {
        return goodSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_sort
     *
     * @param goodSort the value for goods.good_sort
     *
     * @mbg.generated
     */
    public void setGoodSort(Integer goodSort) {
        this.goodSort = goodSort;
    }
}