package com.kgc.provider.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table shoppingcart
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Shoppingcart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.good_image
     *
     * @mbg.generated
     */
    private String goodImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.good_name
     *
     * @mbg.generated
     */
    private String goodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.good_content
     *
     * @mbg.generated
     */
    private String goodContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.good_price
     *
     * @mbg.generated
     */
    private Double goodPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.good_amount
     *
     * @mbg.generated
     */
    private Integer goodAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.id
     *
     * @return the value of shoppingcart.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.id
     *
     * @param id the value for shoppingcart.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.good_image
     *
     * @return the value of shoppingcart.good_image
     *
     * @mbg.generated
     */
    public String getGoodImage() {
        return goodImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.good_image
     *
     * @param goodImage the value for shoppingcart.good_image
     *
     * @mbg.generated
     */
    public void setGoodImage(String goodImage) {
        this.goodImage = goodImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.good_name
     *
     * @return the value of shoppingcart.good_name
     *
     * @mbg.generated
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.good_name
     *
     * @param goodName the value for shoppingcart.good_name
     *
     * @mbg.generated
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.good_content
     *
     * @return the value of shoppingcart.good_content
     *
     * @mbg.generated
     */
    public String getGoodContent() {
        return goodContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.good_content
     *
     * @param goodContent the value for shoppingcart.good_content
     *
     * @mbg.generated
     */
    public void setGoodContent(String goodContent) {
        this.goodContent = goodContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.good_price
     *
     * @return the value of shoppingcart.good_price
     *
     * @mbg.generated
     */
    public Double getGoodPrice() {
        return goodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.good_price
     *
     * @param goodPrice the value for shoppingcart.good_price
     *
     * @mbg.generated
     */
    public void setGoodPrice(Double goodPrice) {
        this.goodPrice = goodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.good_amount
     *
     * @return the value of shoppingcart.good_amount
     *
     * @mbg.generated
     */
    public Integer getGoodAmount() {
        return goodAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.good_amount
     *
     * @param goodAmount the value for shoppingcart.good_amount
     *
     * @mbg.generated
     */
    public void setGoodAmount(Integer goodAmount) {
        this.goodAmount = goodAmount;
    }
}