package com.kgc.provider.mapper;

import com.kgc.provider.dto.GoodsGroup;
import com.kgc.provider.dto.GoodsGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    long countByExample(GoodsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    int deleteByExample(GoodsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    int insert(GoodsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    int insertSelective(GoodsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    List<GoodsGroup> selectByExample(GoodsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    GoodsGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsGroup record, @Param("example") GoodsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsGroup record, @Param("example") GoodsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsGroup record);
}